apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: sommerstudent-skjelett-henrikhorluck
  namespace: sommerstudenter2021
  labels:
    team: sommerstudenter2021
spec:
  image: {{image}} # Fikses av .github/workflows/main.yaml
  liveness:
    path: /isalive
    port: 8080
    initialDelay: 20
    timeout: 60
  readiness:
    path: /isready
    port: 8080
    initialDelay: 20
    timeout: 60
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  ingresses:
    - https://sommerstudent-skjelett-henrikhorluck.dev.intern.nav.no # Fyll inn metedata.name sin verdi her!
  kafka:
    # Husk at dere må oppdatere (les: lage PR) her:
    # https://github.com/navikt/sommerstudent-daemon/blob/main/nais/topic-sommerstudent.yaml#L21
    pool: nav-dev
